version: '3'
networks:
  db:
  web:
services:
  db:
    image: mongo:3.4.10
    volumes:
      - ./data:/data/db
    networks:
      - db
  services:
    build:
      context: .
      args:
        - VERSION=local
    image: cryptonote-wwl:local
    volumes:
      - .:/app
    ports:
      - 5002:5000
    networks:
      - web
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_SERVER=db
      - DB_NAME=wwl
      - PORT=5000
